language: ruby
script: "bundle exec rake run"

rvm:
  - 1.9.3
  - 2.0.0
env:
  global:
    - TIMEOUT=1
  matrix:
    - REDIS_BRANCH=2.4
    - REDIS_BRANCH=2.6
    - REDIS_BRANCH=2.8
    - REDIS_BRANCH=unstable
