language: ruby
script: "bundle exec rake run"

rvm:
  - 1.9.3
gemfile:
  - .travis/Gemfile.redis-gem-3.0
  - .travis/Gemfile.redis-gem-master
env:
  global:
    - TIMEOUT=1
  matrix:
    - REDIS_BRANCH=2.4
    - REDIS_BRANCH=2.6
    - REDIS_BRANCH=2.8
    - REDIS_BRANCH=unstable
